# Generated by Django 3.2.5 on 2022-02-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.CharField(max_length=96),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
