# Generated by Django 3.2.5 on 2022-01-31 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='short_personal_statement',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_genre',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_bio',
            field=models.CharField(blank=True, max_length=520),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(related_name='member_of', to=settings.AUTH_USER_MODEL)),
                ('organisers', models.ManyToManyField(related_name='organiser_of', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
