# Generated by Django 3.2.5 on 2022-03-27 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecommendedBooks',
            new_name='RecommendedBook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='already_read_books',
        ),
    ]
