# Generated by Django 3.2.5 on 2022-02-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='address',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
