# Generated by Django 3.2.5 on 2022-03-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inbox_count',
            field=models.IntegerField(default=0),
        ),
    ]
