# Generated by Django 3.2.5 on 2022-03-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['date', 'start_time', 'end_time']},
        ),
    ]
