# Generated by Django 3.2.5 on 2022-03-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_chatmodel_messagemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatModel',
            new_name='Chat',
        ),
        migrations.RenameModel(
            old_name='MessageModel',
            new_name='Message',
        ),
    ]
