# Generated by Django 3.2.5 on 2022-03-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_user_inbox_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inbox_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
