# Generated by Django 3.2.5 on 2022-03-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_alter_rating_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='end_time',
        ),
    ]
