# Generated by Django 3.2.5 on 2022-02-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='large_url',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='book',
            name='medium_url',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='book',
            name='small_url',
            field=models.URLField(max_length=512),
        ),
    ]
