# Generated by Django 3.2.5 on 2022-03-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_book_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_books',
            field=models.ManyToManyField(to='bookclub.Book'),
        ),
    ]
