# Generated by Django 3.2.5 on 2022-03-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_auto_20220313_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['date', 'time']},
        ),
    ]
