# Generated by Django 3.2.5 on 2022-03-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_alter_user_inbox_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inbox_count',
            field=models.IntegerField(default=0),
        ),
    ]
