# Generated by Django 4.0.1 on 2022-02-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_auto_20220208_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='meeting_online',
            field=models.BooleanField(default=True),
        ),
    ]
