# Generated by Django 3.2.5 on 2022-01-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_alter_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='London', max_length=30),
        ),
    ]
