# Generated by Django 3.2.5 on 2022-02-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub_company',
            new_name='publisher',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
