# Generated by Django 3.2.5 on 2022-03-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_alter_meeting_options'),
        ('bookclub', '0003_auto_20220313_1721'),
    ]

    operations = [
    ]
