# Generated by Django 3.2.5 on 2022-03-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_user_favourite_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_favourite',
        ),
    ]
