# Generated by Django 3.2.5 on 2022-04-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_alter_user_inbox_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inbox_count',
            field=models.IntegerField(default=None),
        ),
    ]
