# Generated by Django 3.2.5 on 2022-03-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0005_remove_book_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='isbn',
        ),
        migrations.AddField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookclub.book'),
        ),
    ]
